FROM node:16 as base

WORKDIR /home/server/app

COPY package*.json ./

RUN npm install

COPY . .

# using this base to build for development image

FROM base as development

ENV NODE_PATH=./dist

RUN npm run build
